[package]
name = "battlebit-stats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battlebit-api = "0.1.7"
gloo = "0.11.0"
yew = { version = "0.20.0", features = ["csr"] }
ybc = "0.4.0"